#!/usr/bin/env zsh

rbenv_plugin_dir=$HOME/.rbenv/plugins

  if [ -d $HOME/.rbenv ] ; then
      echo "rbenv is already installed."
      exit 0
  fi

# Install rbenv

   git clone git://github.com/sstephenson/rbenv.git $HOME/.rbenv

# Install rbenv plugins

  local plugins
  plugins=(
      "rkh/rbenv-update"
      "sstephenson/rbenv-default-gems"
      "sstephenson/rbenv-gem-rehash"
      "sstephenson/ruby-build"
  )

  for p in $plugins
  do
      git clone git://github.com/${p}.git $rbenv_plugin_dir/$(basename $p)
  done

  cat <<EOF > $HOME/.rbenv/default-gems
bundler
pry
EOF
