#!/usr/bin/env zsh

  DOTFILES_ZSH_DIR=$(cd $(dirname $0) ; pwd)

  for s in $DOTFILES_ZSH_DIR/functions/* ; do
      source $s
  done

  for s in $DOTFILES_ZSH_DIR/*.zsh ; do
      source $s
  done

  bindkey '^Xb' peco-cdr
